-- Tạo cơ sở dữ liệu
CREATE DATABASE THI_TRAC_NGHIEM;
GO

-- Sử dụng cơ sở dữ liệu vừa tạo
USE THI_TRAC_NGHIEM;
GO

-- Bảng Lop
CREATE TABLE Lop (
    MALOP NCHAR(8) PRIMARY KEY,
    TENLOP NVARCHAR(40) UNIQUE NOT NULL
);
GO

-- Bảng MonHoc
CREATE TABLE MonHoc (
    MAMH NCHAR(5) PRIMARY KEY,
    TENMH NVARCHAR(40) UNIQUE NOT NULL
);
GO

-- Bảng SinhVien
CREATE TABLE SinhVien (
    MASV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(40),
    TEN NVARCHAR(10),
    NGAYSINH DATE,
    DIACHI NVARCHAR(100),
    MALOP NCHAR(8),
    FOREIGN KEY (MALOP) REFERENCES Lop(MALOP)
);
GO

-- Bảng GiaoVien
CREATE TABLE GiaoVien (
    MAGV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(40),
    TEN NVARCHAR(10),
    SODTLL NCHAR(15),
    DIACHI NVARCHAR(50)
);
GO

-- Bảng GiaoVien_DangKy
CREATE TABLE GiaoVien_DangKy (
    MAGV NCHAR(8),
    MALOP NCHAR(8),
    MAMH NCHAR(5),
    TRINHDO NCHAR(1) CHECK (TRINHDO IN ('A', 'B', 'C')),
    NGAYTHI DATETIME DEFAULT GETDATE(),
    LAN SMALLINT CHECK (LAN >= 1 AND LAN <= 2),
    SOCAUTHI SMALLINT CHECK (SOCAUTHI >= 10 AND SOCAUTHI <= 100),
    THOIGIAN SMALLINT CHECK (THOIGIAN >= 5 AND THOIGIAN <= 60),
    PRIMARY KEY (MALOP, MAMH, LAN),
    FOREIGN KEY (MAGV) REFERENCES GiaoVien(MAGV),
    FOREIGN KEY (MALOP) REFERENCES Lop(MALOP),
    FOREIGN KEY (MAMH) REFERENCES MonHoc(MAMH)
);
GO

-- Bảng BoDe
CREATE TABLE BoDe (
    MAMH NCHAR(5),
    CAUHOI INT IDENTITY(1,1) PRIMARY KEY,
    TRINHDO NCHAR(1) CHECK (TRINHDO IN ('A', 'B', 'C')),
    NOIDUNG NVARCHAR(200),
    A NVARCHAR(50),
    B NVARCHAR(50),
    C NVARCHAR(50),
    D NVARCHAR(50),
    DAP_AN NCHAR(1) CHECK (DAP_AN IN ('A', 'B', 'C', 'D')),
    MAGV NCHAR(8),
    FOREIGN KEY (MAMH) REFERENCES MonHoc(MAMH),
    FOREIGN KEY (MAGV) REFERENCES GiaoVien(MAGV)
);
GO

-- Bảng BangDiem
CREATE TABLE BangDiem (
    MASV NCHAR(8),
    MAMH NCHAR(5),
    LAN SMALLINT CHECK (LAN >= 1 AND LAN <= 2),
    NGAYTHI DATE,
    DIEM FLOAT CHECK (DIEM >= 0 AND DIEM <= 10),
    PRIMARY KEY (MASV, MAMH, LAN),
    FOREIGN KEY (MASV) REFERENCES SinhVien(MASV),
    FOREIGN KEY (MAMH) REFERENCES MonHoc(MAMH)
);
GO

-- Bảng User (do 'User' là từ khóa hệ thống nên phải đặt trong [ ])
CREATE TABLE [User] (
    LOGIN NCHAR(50) PRIMARY KEY,
    PASSWORD NCHAR(50) NOT NULL,
    ROLE NCHAR(10) CHECK (ROLE IN ('PGV', 'GiaoVien', 'SinhVien'))
);
GO

-- Dữ liệu mẫu
INSERT INTO Lop (MALOP, TENLOP) VALUES ('LOP01', 'CNTT01');
INSERT INTO MonHoc (MAMH, TENMH) VALUES ('MH01', 'CSDL');
INSERT INTO [User] (LOGIN, PASSWORD, ROLE) VALUES ('admin', 'admin123', 'PGV');
GO
